// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddArrangementBlockReducer from "../add_arrangement_block_reducer";
import AddNoteReducer from "../add_note_reducer";
import ClearNotesReducer from "../clear_notes_reducer";
import ClearPatternNotesReducer from "../clear_pattern_notes_reducer";
import CreatePatternReducer from "../create_pattern_reducer";
import CreateTrackReducer from "../create_track_reducer";
import JoinSessionReducer from "../join_session_reducer";
import RemoveArrangementBlockReducer from "../remove_arrangement_block_reducer";
import RemoveNoteReducer from "../remove_note_reducer";
import RemoveTrackReducer from "../remove_track_reducer";
import RenamePatternReducer from "../rename_pattern_reducer";
import SetActiveTrackReducer from "../set_active_track_reducer";
import SetPatternBarsReducer from "../set_pattern_bars_reducer";
import SetPlaybackReducer from "../set_playback_reducer";
import SetTimeSignatureReducer from "../set_time_signature_reducer";
import SetVolumeReducer from "../set_volume_reducer";
import SetupDefaultSessionReducer from "../setup_default_session_reducer";
import ToggleMuteReducer from "../toggle_mute_reducer";

export type AddArrangementBlockParams = __Infer<typeof AddArrangementBlockReducer>;
export type AddNoteParams = __Infer<typeof AddNoteReducer>;
export type ClearNotesParams = __Infer<typeof ClearNotesReducer>;
export type ClearPatternNotesParams = __Infer<typeof ClearPatternNotesReducer>;
export type CreatePatternParams = __Infer<typeof CreatePatternReducer>;
export type CreateTrackParams = __Infer<typeof CreateTrackReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type RemoveArrangementBlockParams = __Infer<typeof RemoveArrangementBlockReducer>;
export type RemoveNoteParams = __Infer<typeof RemoveNoteReducer>;
export type RemoveTrackParams = __Infer<typeof RemoveTrackReducer>;
export type RenamePatternParams = __Infer<typeof RenamePatternReducer>;
export type SetActiveTrackParams = __Infer<typeof SetActiveTrackReducer>;
export type SetPatternBarsParams = __Infer<typeof SetPatternBarsReducer>;
export type SetPlaybackParams = __Infer<typeof SetPlaybackReducer>;
export type SetTimeSignatureParams = __Infer<typeof SetTimeSignatureReducer>;
export type SetVolumeParams = __Infer<typeof SetVolumeReducer>;
export type SetupDefaultSessionParams = __Infer<typeof SetupDefaultSessionReducer>;
export type ToggleMuteParams = __Infer<typeof ToggleMuteReducer>;

