// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ContinuationNote,
} from "./types";

export default {
  patternId: __t.u32(),
  trackId: __t.u32(),
  sourceBar: __t.u32(),
  expectedNumBars: __t.u32(),
  expectedStepsPerBar: __t.u32(),
  get expectedSource() {
    return __t.array(ContinuationNote);
  },
  get notes() {
    return __t.array(ContinuationNote);
  },
};
