// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  noteId: __t.u32().primaryKey().name("note_id"),
  patternId: __t.u32().name("pattern_id"),
  trackId: __t.u32().name("track_id"),
  step: __t.u16(),
  pitch: __t.u8(),
  velocity: __t.u8(),
  creatorIdentity: __t.identity().name("creator_identity"),
});
