// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u32().primaryKey().name("session_id"),
  name: __t.string(),
  tempoBpm: __t.u32().name("tempo_bpm"),
  isPlaying: __t.bool().name("is_playing"),
  currentBeat: __t.f64().name("current_beat"),
  timeSigTop: __t.u32().name("time_sig_top"),
  timeSigBottom: __t.u32().name("time_sig_bottom"),
});
