// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  trackId: __t.u32().primaryKey().name("track_id"),
  sessionId: __t.u32().name("session_id"),
  instrument: __t.string(),
  ownerIdentity: __t.identity().name("owner_identity"),
  color: __t.string(),
  isMuted: __t.bool().name("is_muted"),
  volume: __t.f32(),
});
