// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArrangementBlock = __t.object("ArrangementBlock", {
  blockId: __t.u32(),
  sessionId: __t.u32(),
  patternId: __t.u32(),
  position: __t.u32(),
});
export type ArrangementBlock = __Infer<typeof ArrangementBlock>;

export const Note = __t.object("Note", {
  noteId: __t.u32(),
  patternId: __t.u32(),
  trackId: __t.u32(),
  step: __t.u16(),
  pitch: __t.u8(),
  velocity: __t.u8(),
  duration: __t.u16(),
  creatorIdentity: __t.identity(),
});
export type Note = __Infer<typeof Note>;

export const Pattern = __t.object("Pattern", {
  patternId: __t.u32(),
  sessionId: __t.u32(),
  name: __t.string(),
  color: __t.string(),
  numBars: __t.u32(),
});
export type Pattern = __Infer<typeof Pattern>;

export const Session = __t.object("Session", {
  sessionId: __t.u32(),
  name: __t.string(),
  tempoBpm: __t.u32(),
  isPlaying: __t.bool(),
  currentBeat: __t.f64(),
  timeSigTop: __t.u32(),
  timeSigBottom: __t.u32(),
});
export type Session = __Infer<typeof Session>;

export const Track = __t.object("Track", {
  trackId: __t.u32(),
  sessionId: __t.u32(),
  instrument: __t.string(),
  ownerIdentity: __t.identity(),
  color: __t.string(),
  isMuted: __t.bool(),
  volume: __t.f32(),
});
export type Track = __Infer<typeof Track>;

export const UserPresence = __t.object("UserPresence", {
  identity: __t.identity(),
  sessionId: __t.u32(),
  username: __t.string(),
  activeTrackId: __t.u32(),
  lastSeen: __t.timestamp(),
});
export type UserPresence = __Infer<typeof UserPresence>;

